export const adwiteeya = {
  personal_info: {
    name: "Adwiteeya Bhavsar",
    location: "Mumbai, Maharashtra, India - 400012",
    phone: "8591368532",
    email: "adwiteeyabhavsar@gmail.com",
    linkedin: "https://www.linkedin.com/in/adwiteeya-bhavsar/",
  },
  career_objective: `B2B Growth Strategist | Brand Builder \nStrategic marketing professional with 3+ years of experience driving brand growth, building GTM strategies, and generating high-impact leads across global markets. Proven track record of leading teams, optimizing budgets, and delivering measurable business outcomes.`,
  education: [
    {
      degree: "M.M.S. (Marketing)",
      institution: "SIES",
      year: 2024,
      percentage: "77.56%",
    },
    {
      degree: "B.E.",
      institution: "MHSSCOE",
      year: 2019,
      percentage: "73.80%",
    },
    {
      degree: "HSC",
      institution: "MSBSHSE",
      year: 2015,
      percentage: "87.54%",
    },
    {
      degree: "SSC",
      institution: "MSBSHSE",
      year: 2013,
      percentage: "94.20%",
    },
    {
      exam: "CMAT 2022",
      percentile: "99.3",
      rank: "AIR 376",
      year: 2022,
    },
    {
      exam: "CET 2022",
      percentile: "99",
      year: 2022,
    },
  ],
  skills: [
    "B2B Marketing Strategy",
    "Digital Campaign Management",
    // "DCM: Google Ads, Meta Ads",
    "Lead Generation & Nurturing",
    "Marketing Automation",
    "Social Media Strategy & Management",
    "Content Marketing & Copywriting",
    "Analytics & Data-Driven Decisions",
    "Budget Planning & Cost Optimization",
    "Market Research & Competitive Analysis",
    "Team Leadership",
  ],
  tools: [
    "Hootsuite",
    "Zoho Campaigns",
    "Google Analytics",
    "SEMRUSH",
    "SurferSEO",
  ],
  publication: {
    title: "The Impact of Social Media on Consumer Buying Behavior",
    journal: "SIES Journal of Management",
    year: "2022-23",
  },
  professional_experience: [
    {
      role: "Executive → Sr. Executive → Assistant Manager, Brand & Marketing",
      company: "Supersonic Distribution and Services Pvt. Ltd.",
      duration: "May 2024 - Present",
      achievements: [
        "Strong interest in fintech products, including invoice financing, digital payments, and blockchain; continuously reading and staying updated to align marketing strategies with industry trends.",
        "Assisted in managing public relations efforts, media engagement, and establishing the company’s thought leadership within the sector.",
        "Conducted segmentation of customer data to develop highly targeted, persona-driven marketing campaigns addressing specific pain points.",
        "Collaborated with external vendors and agencies to ensure the timely and effective delivery of marketing campaigns.",
        "Led initiatives to elevate brand awareness by participating in industry forums, webinars, and conferences.",
        // "Reduced marketing costs by ₹1 lakh( ~7 percent of budget) through effective negotiation and cost-efficient promotional strategies.",
        "Led B2B marketing strategy while managing and mentoring a high-performing team of 4 to drive brand growth and expand into the Middle East market.",
        "Built Supersonic’s brand from scratch, including brand guidelines, positioning, visual assets, and a corporate video that boosted visibility.",
        "Currently leading SEO, GEO, and AEO initiatives to drive ongoing content visibility and discovery across search engines, generative AI tools, and answer-focused platforms.",
        "Excelled at the Gulfood Expo with the team, securing 25+ potential high-value deals and engaging 100+ global buyers.",
        "Directed end-to-end lead generation through campaigns, partnerships, and memberships—resulting in 1,400+ qualified leads.",
        // "Reduced marketing costs by ₹1 lakh+ through effective negotiation and cost-efficient promotional strategies.",
        "Reduced marketing costs by ₹1 lakh( ~7 percent of budget) through effective negotiation and cost-efficient promotional strategies.",
        "Utilized SEMrush to enhance website performance through targeted keyword research, content optimization, and strategic blog planning, driving measurable improvements in search engine results page (SERP) rankings.",
        "Established the marketing foundation for Aasisa Ventures, including a strong website and essential marketing materials.",
        "Led competitive research initiatives, helping position the brand for success in new markets.",
        "Strengthened collaboration across sales, design, and digital teams to accelerate marketing execution.",
        "Achieved a social score of 947/1000 across platforms by driving consistent growth through tailored digital strategies and content.",
      ],
    },
    {
      role: "Marketing Intern",
      company: "ASAP Realtech",
      duration: "May 2023 - July 2023",
      achievements: [
        "Transformed campaign precision with deep market and competitor analysis for 10+ real estate projects.",
        "Recruited 7 partners, amplifying project reach by 30%.",
        "Closed a high-value property sale with elite market insights.",
      ],
    },
    {
      role: "Digital Marketing Executive & Market Research Analyst",
      company: "Online NEET Education",
      duration: "Sept 2020 - Sept 2022",
      achievements: [
        "Increased enrollment by 47% through a targeted high-ROI marketing strategy, optimizing ad spend.",
        "Leveraged data from over 150 students to create actionable insights, driving a 20% increase in conversion rates.",
        "Analyzed market trends and competitor data to inform product positioning and pricing adjustments.",
      ],
    },
    {
      role: "Graduate Apprentice Trainee",
      company: "Mahindra and Mahindra Ltd. (Automotive)",
      duration: "Aug 2019 - Aug 2020",
    },
  ],
};
